server:
  port: 9988
  
#security:
#  oauth2:
#    registration:
#          google:
#            client-id: your-app-client-id
#            client-secret: your-app-client-secret
#          github:
#            client-id: your-app-client-id
#            client-secret: your-app-client-secret
#          facebook:
#            client-id: your-app-client-id
#            client-secret: your-app-client-secret
#          okta:
#            client-id: your-app-client-id
#            client-secret: your-app-client-secret